version: '{branch}-{build}'
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore CSF.Screenplay.sln

    copy /y Tests\CSF.Screenplay.Web.Tests\App.config.AppVeyor Tests\CSF.Screenplay.Web.Tests\App.config
services:
  - iis
build:
  project: CSF.Screenplay.sln
  verbosity: normal
test:
  assemblies:
    except:
    - '**\CSF.Screenplay.Web.Tests.dll'
    - '**\Ploeh.AutoFixture.NUnit3.dll'
    - '**\CSF.Screenplay.NUnit.dll'
artifacts:
  - path: Tests\CSF.Screenplay.WebTestWebsite
    name: TestWebsite
    type: WebDeployPackage
deploy:
  - provider: Local
    TestWebsite.deploy_website: true
    TestWebsite.site_name: "Default Web Site"
after_deploy:
- cmd: nunit3-console.exe Tests\CSF.Screenplay.Web.Tests\bin\Debug\CSF.Screenplay.Web.Tests.dll
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))