version: '{branch}-{build}'
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    git submodule update --init --recursive
    
    nuget restore CSF.Screenplay.sln
    
    copy /y Tests\CSF.Screenplay.Web.Tests\App.config.AppVeyor Tests\CSF.Screenplay.Web.Tests\App.config
build:
  project: CSF.Screenplay.sln
  verbosity: normal
artifacts:
- path: Tests\CSF.Screenplay.WebTestWebsite
  name: TestWebsite
  type: WebDeployPackage
deploy:
- provider: Local
  TestWebsite.deploy_website: true
  TestWebsite.port: 8080
  TestWebsite.ip: 127.0.0.1
  TestWebsite.hostname: localhost
  TestWebsite.remove_files: true
test:
  assemblies:
    except:
    - '**\Ploeh.AutoFixture.NUnit3.dll'
    - '**\CSF.Screenplay.NUnit.dll'
