language: csharp
solution: CSF.Screenplay.sln

before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number

install:
  - mono .nuget/nuget.exe restore CSF.Screenplay.sln
  - mono .nuget/nuget.exe install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Debug CSF.Screenplay.sln
  - mono "./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe" $(find ./Tests/ -type f -path "*/bin/Debug/*" -name "CSF.*.Tests.dll" \! -name "CSF.Screenplay.Web.Tests.dll")