language: csharp
solution: CSF.Screenplay.sln

install:
  - nuget restore CSF.Screenplay.sln
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Debug CSF.Screenplay.sln
  - mono "./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe" $(find ./Tests/ -type f -path "*/bin/Debug/*" -name "CSF.*.Tests.dll" \! -name "CSF.Screenplay.Web.Tests.dll")